apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterrole.name }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - policy
    resourceNames:
    - {{ .Values.podsecuritypolicy.name }}
    resources:
    - podsecuritypolicies
    verbs:
    - use