apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.fbinfo.name }}
  namespace: {{ .Values.namespace.name }}
data:
  cluster.name: shoot--ias--{{ .Values.configmap.fbinfo.item }}
  logs.region: {{ .Values.configmap.region }}
  http.server: "On"
  http.port: "2020"
  read.head: "Off"
  read.tail: "On"